### ISSUE TITLE
reservoirYieldMultiplierOverride has no effect

### ISSUE THREAD

**Issue by Wags622** [erkle64/OreMultiplier#1]
Chance/Yield for Ore works and Chance for Olumite works, but as title says the yield multiplier for Olumite has no effect
Tried upto 9999999, but all new reservoirs are always 2-8mill liters regardless.

**Comment by erkle64** [comment]
Thank you.  Should be fixed in [v0.2.5](https://github.com/erkle64/OreMultiplier/releases/tag/v0.2.5)
